#include <pebble.h>
  
#ifndef Constants_h
#define Constants_h
  
#define MAX_NUM_INVADERS 33
#define NUM_BULLETS 24
#define NUM_INVADER_BULLETS 30
#define NUM_SHIELD_BLOCKS 90
#define NUM_SHIELD_ROWS 6
#define NUM_SHIELD_COLUMNS 9
#define NUM_ROW1_INVADERS 7
#define NUM_ROW2_INVADERS 6
  
#define TOP_PADDING 18
#define COLUMN_PADDING 5
#define ROW_PADDING 4
  
#define INVADER_HEIGHT 9
#define INVADER_WIDTH 12
#define SHOOTER_WIDTH 25
#define SHOOTER_HEIGHT 15
#define INVADER_BULLET_WIDTH 3
#define INVADER_BULLET_HEIGHT 7 
#define SHOOTER_BULLET_WIDTH 5 
#define SHOOTER_BULLET_HEIGHT 6 
#define POWERUP_BULLET_ANGLE 20
#define SHOOTER_BOTTOM_PADDING 4
#define BLOCK_SIZE 3

#define INVADER_BULLET_LEVEL_CAP 9
#define INVADER_BULLET_MIN_SPEED 550
#define INVADER_BULLET_MAX_SPEED 2200
#define INVADER_BULLET_MIN_DECREASE 50
#define INVADER_BULLET_MAX_DECREASE 200

#define INVADER_SPEED_LEVEL_CAP 11
#define INVADER_MAX_INTERVAL 400
#define INVADER_INTERVAL_DECREASE_PER_LEVEL 37
#define INVADER_MIN_INTERVAL 30
  
#define MIN_ACCELERATION 20
  
#define SHOOTER_FIRE_INTERVAL 350
#define SHOOTER_BULLET_SPEED 4
#define POWERUP_TIME 2500
#define FPS 20

typedef enum direction {
  LEFT,
  RIGHT,
  UP,
  DOWN
} direction; 

typedef enum invader_type {
  INVADER_RESOURCE_HAPPY,
  INVADER_RESOURCE_SQUID,
  INVADER_RESOURCE_POWERUP
} invader_type;

#endif